version: '3'

services:
  db:
    image: bitnami/postgresql
    container_name: car-rental-db
    restart: always
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=car-rental
    ports:
      - 5432:5432
    volumes:
      - ./.pgdata:/bitnami/postgresql

  app:
    build: .
    container_name: car-rental-api
    ports:
      - 3333:3333
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev
